### ISSUE TITLE
V3.0.0 To-Do List in Issue Style, because why not.

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/Universal-Updater#15]
**v2.2.0 will be released in the next days and I'll do the next To-Do list in an Issue style.** 

**This is the To-Do list for v3.0.0, so People can check, what is already done, what not.**

- [ ] Do the Script Creator usable.

- [x] Improvements for Universal-Updater.

- [x] Add a moveFile Function, so People can move / "Backup" files.

- [x] Add QR Code Scanning for UniStore, so you can scan QR Codes from the UniStore site.

- [ ] Unknown yet.

**Comment by SuperSaiyajinStackZ** [comment]
Closing this, because this is done.
