### ISSUE TITLE
Rewrite TODO list

### ISSUE THREAD

**Issue by Epicpkmn11** [Universal-Team/Universal-Updater#98]
This is the TODO list for the Universal-Updater rewrite to make the code-base cleaner and easier to work with. It will be updated over time.

### Shared
- [ ] Action classes: Make base header files for the classes, so the implementation can be done as needed on both, the DSi and 3DS side

### 3DS version
- [ ] Work on the action class implementations for the 3DS version

### DSi version
- [ ] Work on the action class implementations for the DSi version
